### ISSUE TITLE
WolfCommand.getTarget(...) limited to a distance of 16 blocks

### ISSUE THREAD

**Issue by Cameri** [puppyize/WolfCommand#11]
LivingEntity.setTarget(...) is limited to 16 blocks of distance because the path finder function is being called with a hardcoded 16F.
Only wolves within 16 blocks of the said entity will attack, others will stay put.

**Comment by puppyize** [comment]
Still a problem over a year later..... :sweat: 

Been working on a solution to this... and have it actually working for long distance attacking... so the 40 block limit / extender is working fantastically, using custom overridded NMS classes, but the wolves are now moving super slow when attacking (appears to be tick-based motion), so there's still a couple more steps to getting it to production, but it's looking really really close to done!

Plan to migrate out of NMS requirements after getting this resolved so that it's not affected when the servers are updated....
